<a href="https://colab.research.google.com/github/CelesTech03/Data-Analytics-Winter-2022/blob/main/Python/Day_5_Intro_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Intro to NumPY

In [ ]:
import numpy as np # Way of renaming package for your convenience

In [ ]:
# one-dimensional array
np_city = np.array(['NYC', 'LA', 'Miami', 'Houston'])
np_city.ndim #gets dimension

1

# Fundamentals

In [ ]:
# .shape = Dimensions of the array. A tuple of integers showing the size
# of the array in each dimension
np_city.shape

(4,)

In [ ]:
# Total number of elements in the array. Equal to the product of the
# elements of shape
np_city.size

4

In [ ]:
# An object describing the type of the elements in the array
# They can be created or specified using Python
np_city.dtype

dtype('<U7')

In [ ]:
# np_city is one-dimensional and np_city2 is two-dimensional
np_city2 = np.array([['NYC', 'LA', 'Maimi', 'Houston'], 
                     ['NY', 'CA', 'FL', 'TX']])
np_city2.ndim

2

In [ ]:
# The shape tuple of both the arrays indicate their size along each dimension.
np_city2.shape

(2, 4)

In [ ]:
np_city2.dtype

dtype('<U7')

In [ ]:
# Gets the amount of elements in the array
np_city2.size

8

In [ ]:
# Create a np array with 5 Lists in it
# each list must have 10 items in it

np_colors = np.array([['Red', 'Green', 'Blue', 'Pink', 'Yellow', 'Brown', 'White', 'Purple', 'Orange', 'Gray'],
                     ['Red', 'Green', 'Blue', 'Pink', 'Yellow', 'Brown', 'White', 'Purple', 'Orange', 'Gray'],
                     ['Red', 'Green', 'Blue', 'Pink', 'Yellow', 'Brown', 'White', 'Purple', 'Orange', 'Gray'],
                     ['Red', 'Green', 'Blue', 'Pink', 'Yellow', 'Brown', 'White', 'Purple', 'Orange', 'Gray'],
                     ['Red', 'Green', 'Blue', 'Pink', 'Yellow', 'Brown', 'White', 'Purple', 'Orange', 'Gray']])

In [ ]:
np_colors.shape

(5, 10)

In [ ]:
np_city2.dtype

dtype('<U7')

In [ ]:
np_city2.size

8

#Basic Operations

In [ ]:
# NumPy uses the indices of the elements in each array to carry out basic operations. 
# In this case, where we are looking at a dataset of four cyclists during two trials, vector addition of the arrays gives the required output.
first_trial_cyclist = [10, 15, 17, 26, 37, 49, 57, 61]

In [ ]:
second_trial_cyclist = [11, 45, 65, 24, 23, 45, 90, 99]

In [ ]:
np_first_trial = np.array(first_trial_cyclist)
np_second_trial = np.array(second_trial_cyclist) 

In [ ]:
np_first_trial + np_second_trial

array([ 21,  60,  82,  50,  60,  94, 147, 160])

In [ ]:
np_first_trial[1] * np_second_trial[5]

675

#Accessing elements

In [ ]:
cyclist_trial = np.array([[10, 15, 17, 26],[12, 11, 21, 24]])

In [ ]:
# You can access an entire row of an array by referencing its axis index.
ftrial = cyclist_trial[0]
ftrial

array([10, 15, 17, 26])

In [ ]:
# First cyclist: all trial data. Use ':' to select all the rows of an array
first_cyclist_all_trials = cyclist_trial[:,0]
first_cyclist_all_trials

array([10, 12])

In [ ]:
newlist = ['string1', 'string2']

In [ ]:
newlist[0]

'string1'

In [ ]:
newlist[0][2] # Gets the second elements of the first set data

'r'

In [ ]:
strail = cyclist_trial[1]

In [ ]:
strail

array([12, 11, 21, 24])

In [ ]:
ftrial[1] # This is the same as saying cyclist_trial[0][1]

15

In [ ]:
cyclist_trial[0][1]

15

In [ ]:
# Boolean arrays are useful when you need to select a dataset according to set criteria. 
# Here, the original dataset contains test scores of two students. You can use a Boolean array to choose 
# only the scores that are above a given value.
test_score = np.array([[83, 71, 67, 63], 
                       [54, 68, 81, 45]])

passed = test_score > 60
passed

array([[ True,  True,  True,  True],
       [False,  True,  True, False]])

In [ ]:
# Send "passing score" as an argument to "test scores" object
test_score[passed]

array([83, 71, 67, 63, 68, 81])

In [ ]:
test2_scores = test_score

In [ ]:
test_score is test2_scores

True

In [ ]:
test2_scores[1][3] = 78

In [ ]:
test2_scores

array([[83, 71, 67, 63],
       [54, 68, 81, 78]])

In [ ]:
test_score

array([[83, 71, 67, 63],
       [54, 68, 81, 78]])

In [ ]:
# When working with arrays, data is copied into new arrays only in some cases. Following are the three possible scenarios:
NYC_Borough = np.array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'])
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

# View/Shallow Copy
When working with arrays, data is copied into new arrays only in some cases. Following are the three possible scenarios:

In [ ]:
# In this method, a variable is directly assigned the value of another. No new copy is made
Boroughs_in_NYC = NYC_Borough
Boroughs_in_NYC # Prints assigned dataset

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [ ]:
Boroughs_in_NYC is NYC_Borough

True

In [ ]:
len(Boroughs_in_NYC)

5

In [ ]:
Boroughs_in_NYC 

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [ ]:
# A view, also referred to as a shallow copy, creates a new array object
View_of_Borough_in_NYC = Boroughs_in_NYC.view()

In [ ]:
len(Boroughs_in_NYC)

5

In [ ]:
View_of_Borough_in_NYC[4] = 'Central Park' # Change value in "view object"
View_of_Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [ ]:
Boroughs_in_NYC # Original dataset is changed

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

# Deep Copy
Copy is also called "deep copy" because it entirely copies the original dataset.
Any change in the copy will not affect the orginal dataset.

In [ ]:
Copy_of_NYC_Borough = NYC_Borough.copy()

In [ ]:
# Shows "copy" and original object are different
Copy_of_NYC_Borough is NYC_Borough 

False

In [ ]:
# Shows "copy" object data is not owned by the original dataset
Copy_of_NYC_Borough.base is NYC_Borough 

False

In [ ]:
Copy_of_NYC_Borough[4] = 'Astoria' # Change value in "copy"
NYC_Borough # "Copy" object changed

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [ ]:
Copy_of_NYC_Borough # Original dataset retained

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Astoria'],
      dtype='<U13')

#Universal Functions
NumPy provides useful mathematical functions called Universal Functions. These functions operate element-wise on an array, producing another array as output.

In [ ]:
np_sqrt = np.sqrt([2,4,9,16])
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

In [ ]:
from numpy import pi

In [ ]:
np.cos(0)

1.0

In [ ]:
np.sin(pi/2)

1.0

In [ ]:
np.cos(pi)

-1.0

In [ ]:
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [ ]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

#Broadcasting Techniques

In [ ]:
# NumPy uses broadcasting to carry out arithmetic operations between arrays of different shapes. In this method, NumPy automatically broadcasts the smaller array over the larger array. 
# Create two arrays of the same shape
array_a = np.array([2, 3, 5, 8])
array_b = np.array([.3, .3, .3, .3])

In [ ]:
# Multiply arrays
array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [ ]:
# Create a variable with a scalar value
scalar_c = .3

In [ ]:
# Multiply 1D array with a scalar value
array_a * scalar_c

array([0.6, 0.9, 1.5, 2.4])

#Linear Algebra

In [ ]:
# NumPy can carry out linear algebraic functions as well. 
# The “transpose()” function can help you interchange rows as columns, and vice-versa.
test_scores = np.array([[83,71,57,63], [54,68,81,45]])
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [ ]:
# Using NumPy, you can also find the inverse of an array and add its diagonal data elements.
inverse_array = np.array ([[10,20],[15,25]])
np.linalg.inv(inverse_array) # Inverse of given array

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [ ]:
trace_array = np.array([[10,20],[22,31]])
np.trace(trace_array) # Sums elements 10 and 31

41